name: Deploy Lambda Function for production release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6     
      - name: Install app dependencies
        run: |
          pip install --upgrade pip pipenv
          pipenv sync --dev
      - name: Lint with flake8
        run: |
          pipenv run flake8 app tests
      - name: Test with pytest
        run: |
          pipenv run pytest
      - name: Notify result to slack
        uses: homoluctus/slatify@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*Deploy Lambda for production(build)*"
          channel: '#sandbox-amotz'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Setup Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Serverless Framework
        run: |
          npm install serverless -g          
      - name: Install app dependencies
        run: |
          pip install --upgrade pip pipenv
          pipenv sync --dev
      - name: Deploy Lambda Function with sls
        run: |
          sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Notify result to slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "*Deploy Lambda for production*"
          channel: '#sandbox-amotz'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
