name: Python Build

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipfile-requirements
        pipfile2req > requirements.txt
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 app tests

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipfile-requirements
        pipfile2req > requirements.txt
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest

